import picture1 from "..//..//Slide/495D0A.jpg"
import picture2 from '..//..//Slide/4828F3.jpg';
import picture3 from '..//..//Slide/D42A24.jpg';
export const products = [
    {
      id: 1,
      name: 'Event 1',
      date: "6/10/2015",
      image:  picture1 ,
      category: "Live music",
    },
    {
      id: 2,
      name: 'Event 2',
      date: "6/10/2015",
      image: picture2 ,
      category: "Art & Culture",
    },
    {
      id: 3,
      name: 'Event 3',
      date: "6/10/2015",
      image: picture3,
      category: "Nightlife",
    },
    {
      id: 4,
      name: 'Event 4',
      date: "6/10/2015",
      image: picture1 ,
      category: "Community",
    },
    {
      id: 5,
      name: 'Event 5',
      date: "6/10/2015",
      image: picture2,
      category: "Course",
    },
    {
      id: 6,
      name: 'Event 6',
      date: "6/10/2015",
      image: picture3,
      category: "Attractions",
    },
    {
      id: 7,
      name: 'Event 7',
      date: "6/10/2015",
      image: picture1,
      category: "Sport",
    },
    {
      id: 8,
      name: 'Event 8',
      date: "6/10/2015",
      image: picture2,
      category: "Live music",
    },
    {
      id: 9,
      name: 'Event 1',
      date: "6/10/2015",
      image:  picture1 ,
      category: "Live music",
    },
    {
      id: 10,
      name: 'Event 2',
      date: "6/10/2015",
      image: picture2 ,
      category: "Live music",
    },
    {
      id: 11,
      name: 'Event 3',
      date: "6/10/2015",
      image: picture3,
      category: "Live music",
    },
    {
      id: 12,
      name: 'Event 4',
      date: "6/10/2015",
      image: picture1 ,
      category: "Live music",
    },
    {
      id: 13,
      name: 'Event 5',
      date: "6/10/2015",
      image: picture2,
      category: "Live music",
    },
    {
      id: 14,
      name: 'Event 6',
      date: "6/10/2015",
      image: picture3,
      category: "Live music",
    },
    {
      id: 15,
      name: 'Event 7',
      date: "6/10/2015",
      image: picture1,
      category: "Live music",
    },
    {
      id: 16,
      name: 'Event 8',
      date: "6/10/2015",
      image: picture2,
      category: "Live music",
    },
  ];

